### ISSUE TITLE
LoadError: cannot load such file -- capistrano/log_with_awesome

### ISSUE THREAD

**Issue by satboy78** [jnewland/capistrano-log_with_awesome#2]
Hi,
I'm trying to use log_with_awesome in my new capistrano v3 deploy script, but after installing it I get this error 

LoadError: cannot load such file -- capistrano/log_with_awesome

Do I have to change version to any gem?

Can you please help me?

Thanks a lot.

Best regards,
Matteo

---

GEMFILE
source "https://rubygems.org"
gem "capistrano", ">=3.0.0"
gem "capistrano-multiconfig", ">=3.0.3"
gem 'capistrano-symfony', '~> 0.1'
gem 'capistrano-composer'
gem 'capistrano-file-permissions'
gem 'capistrano-log_with_awesome'
gem 'cap-ec2'

---

CAPFILE
require 'capistrano/multiconfig'
require 'capistrano/deploy'
require "cap-ec2/capistrano"
require 'capistrano/symfony'
require 'capistrano/file-permissions'
require 'capistrano/composer'
require 'capistrano/log_with_awesome'

---

GEMFILE.LOCK
GEM
  remote: https://rubygems.org/
  specs:
    aws-sdk-v1 (1.64.0)
      json (~> 1.4)
      nokogiri (>= 1.4.4)
    cap-ec2 (1.0.0)
      aws-sdk-v1
      capistrano (>= 3.0)
      colorize
      terminal-table
    capistrano (3.4.0)
      i18n
      rake (>= 10.0.0)
      sshkit (~> 1.3)
    capistrano-bower (1.1.0)
      capistrano (~> 3.0)
    capistrano-composer (0.0.6)
      capistrano (>= 3.0.0.pre)
    capistrano-file-permissions (0.1.1)
      capistrano (~> 3.1)
    capistrano-grunt (0.0.4)
      capistrano (>= 3.0.0.pre)
    capistrano-log_with_awesome (0.0.2)
      capistrano (>= 2.5.14)
    capistrano-multiconfig (3.0.8)
      capistrano (>= 3.0.0)
    capistrano-npm (1.0.1)
      capistrano (>= 3.0.0)
    capistrano-symfony (0.4.0)
      capistrano (~> 3.1)
      capistrano-composer (~> 0.0.3)
      capistrano-file-permissions (~> 0.1.0)
    colorize (0.7.7)
    i18n (0.7.0)
    json (1.8.2)
    mini_portile (0.6.2)
    net-scp (1.2.1)
      net-ssh (>= 2.6.5)
    net-ssh (2.9.2)
    nokogiri (1.6.6.2)
      mini_portile (~> 0.6.0)
    rake (10.4.2)
    sshkit (1.7.1)
      colorize (>= 0.7.0)
      net-scp (>= 1.1.2)
      net-ssh (>= 2.8.0)
    terminal-table (1.4.5)

---

FULL TRACE
cap aborted!
NameError: uninitialized constant Capistrano::Logger
/var/lib/gems/2.1.0/gems/capistrano-log_with_awesome-0.0.2/lib/capistrano/log_with_awesome.rb:4:in `<module:Capistrano>'
/var/lib/gems/2.1.0/gems/capistrano-log_with_awesome-0.0.2/lib/capistrano/log_with_awesome.rb:3:in`<top (required)>'
/usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `require'
/usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in`rescue in require'
/usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require'
/home/mbruno/Documents/mtv/deploy-tool-cap3/Capfile:21:in`<top (required)>'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/rake_module.rb:28:in `load'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/rake_module.rb:28:in`load_rakefile'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:689:in `raw_load_rakefile'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:94:in`block in load_rakefile'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:93:in`load_rakefile'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:77:in `block in run'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:176:in`standard_exception_handling'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/var/lib/gems/2.1.0/gems/capistrano-3.4.0/lib/capistrano/application.rb:15:in`run'
/var/lib/gems/2.1.0/gems/capistrano-3.4.0/bin/cap:3:in `<top (required)>'
/usr/local/bin/cap:23:in`load'
/usr/local/bin/cap:23:in `<main>'
LoadError: cannot load such file -- capistrano/log_with_awesome
/usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in`require'
/usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `require'
/home/mbruno/Documents/mtv/deploy-tool-cap3/Capfile:21:in`<top (required)>'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/rake_module.rb:28:in `load'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/rake_module.rb:28:in`load_rakefile'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:689:in `raw_load_rakefile'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:94:in`block in load_rakefile'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:93:in`load_rakefile'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:77:in `block in run'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:176:in`standard_exception_handling'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/var/lib/gems/2.1.0/gems/capistrano-3.4.0/lib/capistrano/application.rb:15:in`run'
/var/lib/gems/2.1.0/gems/capistrano-3.4.0/bin/cap:3:in `<top (required)>'
/usr/local/bin/cap:23:in`load'
/usr/local/bin/cap:23:in `<main>'

**Comment by technicalpickles** [comment]
> NameError: uninitialized constant Capistrano::Logger

This gem hasn't been updated in quite awhile, so it's pretty likely the Capistrano API changed at some point.
